### ISSUE TITLE
Add RexEx to export

### ISSUE THREAD

**Issue by teenrage-dev** [Nikoro/emoji_extension#12]
Hello, please export file **regex.dart**
It's useful in my case, all emojis that u added.
I want to add to TextField to avoid the emogi;
 inputFormatters: [
  FilteringTextInputFormatter.deny(emoji.Regex.emoji),
],

https://github.com/Nikoro/emoji_extension/blob/main/lib/src/regex.dart

**Comment by Nikoro** [comment]
Hi!

In the newest version `1.2.0` I exported the emoji regex.
Usage:
```dart
final regex = Emojis.regex;
  // print(regex); // RegExp: pattern=[#*\d]\uFE0F?\u20E3|[\xA9\...
```
