### ISSUE TITLE
Bump to Unicode Emoji 16.0

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [Nikoro/emoji_extension#15]
The package should be updated to contain Emoji 16.

Additionally, I'd be curious about the scripting to generate the Dart side Emoji Data. It might be helpful to check it in here.

**Comment by Nikoro** [comment]
Hi!

In newest version `1.2.0` I've updated emoji dataset to newest [Unicode 16.0](https://www.unicode.org/reports/tr51/)
